package com.apiturnos.turno.model;

public enum MotivoRechazoTurnoManual {
    DATOS_INVALIDOS,
    CLIENTE_NO_HABILITADO,
    TIPO_ATENCION_INACTIVO,
    DIA_INACTIVO,
    DIA_FINALIZADO,
    ESTADO_DIA_NO_PERMITIDO,
    FECHA_PASADA,
    HORARIO_YA_INICIADO,
    HORARIO_NO_PERTENECE_AL_DIA,
    DIA_CERRADO_POR_EXCEPCION,
    HORARIO_BLOQUEADO_POR_EXCEPCION
}
